void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int getNumSqr(int num, int i);
int is_prime_number(int n);
int getNumPrim(int num, int i);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
int getNumPrim(int num, int i);
int is_palindrome(char *s);
